import os, sys
path = r'd:\hackathon\lib\main.dart'
print(f'File exists: {os.path.exists(path)}')
if os.path.exists(path):
    os.chmod(path, 0o777)
    os.remove(path)
    print('Deleted old file')
with open(path, 'w', encoding='ascii') as f:
    f.write("import 'package:flutter/material.dart';\n")
    f.write("import 'package:flutter_riverpod/flutter_riverpod.dart';\n")
    f.write("import 'core/theme/app_theme.dart';\n")
    f.write("import 'core/routes/app_router.dart';\n")
    f.write("\n")
    f.write("void main() {\n")
    f.write("  WidgetsFlutterBinding.ensureInitialized();\n")
    f.write("  runApp(\n")
    f.write("    const ProviderScope(\n")
    f.write("      child: TourTrackApp(),\n")
    f.write("    ),\n")
    f.write("  );\n")
    f.write("}\n")
    f.write("\n")
    f.write("class TourTrackApp extends ConsumerWidget {\n")
    f.write("  const TourTrackApp({super.key});\n")
    f.write("\n")
    f.write("  @override\n")
    f.write("  Widget build(BuildContext context, WidgetRef ref) {\n")
    f.write("    return MaterialApp.router(\n")
    f.write("      title: 'TourTrack',\n")
    f.write("      debugShowCheckedModeBanner: false,\n")
    f.write("      theme: AppTheme.lightTheme,\n")
    f.write("      darkTheme: AppTheme.darkTheme,\n")
    f.write("      themeMode: ThemeMode.system,\n")
    f.write("      routerConfig: AppRouter.router,\n")
    f.write("    );\n")
    f.write("  }\n")
    f.write("}\n")
print('Written OK')
